version: '3.8'

services:
  db:
    image: mysql:8.0
    container_name: billing-db
    restart: always
    environment:
      MYSQL_DATABASE: jelantik_billing
      MYSQL_ROOT_PASSWORD: ${DATABASE_PASSWORD:-root}
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  backend:
    image: ghcr.io/${REPO_NAME:-ahmad-rizki21/billing-portal_v3.5}-backend:${IMAGE_TAG:-latest}
    build: .
    container_name: billing-backend
    restart: always
    env_file:
      - .env
    environment:
      - DATABASE_URL=mysql+aiomysql://root:${MYSQL_ROOT_PASSWORD:-root}@db:3306/jelantik_billing
    depends_on:
      - db
    ports:
      - "8000:8000"


  frontend:
    image: ghcr.io/${REPO_NAME:-ahmad-rizki21/billing-portal_v3.5}-frontend:${IMAGE_TAG:-latest}
    build:
      context: ./frontend
    container_name: billing-frontend
    restart: always
    depends_on:
      - backend
    ports:
      - "80:80"

volumes:
  mysql_data:
